### ISSUE TITLE
"git_packages" not found

### ISSUE THREAD

**Issue by mkotsbak** [salt-formulas/salt-formula-taiga#2]
I get this:

<pre>
   ID: /srv/taiga/virtualenv
    Function: virtualenv.manage
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     pkg: git_packages
</pre>

Where is this git_packages coming from? Does it require the git formula somehow?

**Comment by mkotsbak** [comment]
Seems to depend on https://github.com/salt-formulas/salt-formula-git yes.

**Comment by fpytloun** [comment]
Yes, it depends on salt-formula-linux. However this formula is pretty old and would deserve a little cleanup = call for volunteers.. ;-)

**Comment by mkotsbak** [comment]
I found the issue. There was a local "git" state here too that conflicted with the dependency. Added PR to update doc about the dependency.
